imgs_directory = './images/'
input_imgs_directory = imgs_directory+'input/'
input_animals_directory = imgs_directory+'input/animals/'
output_imgs_directory = imgs_directory+'output/'
query_img_path = imgs_directory + 'input/captures/remi.jpeg'
target_animal_regexp = '*'
