imgs_directory = './images/'
input_imgs_directory = imgs_directory+'input/'
input_animals_directory = input_imgs_directory+'animals/'
output_imgs_directory = imgs_directory+'output/'
capture_imgs_directory = input_imgs_directory + 'captures/'
query_img_path = capture_imgs_directory+'IMG_20200703_215347.jpg'
target_animal_regexp = '*'
